export const HEADER_ONFOCUS = "HEADER_ONFOCUS";
export const HEADER_ONBLUR = "HEADER_ONBLUR";
export const HEADER_MOUSE = "HEADER_MOUSE";
export const HEADER_LEAVE = "HEADER_LEAVE";
export const HEADER_TRUE = "HEADER_TRUE";
export const HEADER_FALSE = "HEADER_FALSE";
