export const MenuList = [
    {
    title:"首页",
    key:'/admin/home',  
    icon:"book", 
    },
    {
    title:"表单页",
    key:"/admin/form",
    icon:"edit",   
    children:[
        {
            title:"基础表单",
            key:'/admin/form/basic',
            icon: 'safety',     
        },
        {
            title:"分步表单",
            key:'/admin/form/step',
            icon: 'safety',     
        },
        {
            title:"高级表单",
            key:'/admin/form/height',
            icon: 'safety',     
        }
    ] 
    },
    {
        title:"列表",
        key:'/admin/list', 
        icon:"table",
        children:[
            {
                title:"搜索列表",
                key:'/admin/list/search', 
                icon: 'bars'    
            },
            {
                title:"查询表格",
                key:'/admin/list/search-list', 
                icon: 'bars'    
            },
            {
                title:"标准列表",
                key:'/admin/list/basic-list',
                icon: 'bars'     
            },
            {
                title:"卡片列表",
                key:'/admin/list/card-list', 
                icon: 'bars'    
            }
        ]   
    },
    {
        title:"详情页",
        key:'/admin/proflie', 
        icon:"solution",
        children:[
            {
                title:"基础详情",
                key:'/admin/proflie/basic',   
                icon: 'bars'
            },
            {
                title:"高级详情",
                key:'/admin/proflie/height',  
                icon: 'bars' 
            }
        ]    
    },
    {
        title:"结果页",
        key:'/admin/result', 
        icon:"check-circle", 
        children:[
            {
                title:"结果页",
                key:'/admin/result/success', 
                icon:'close'       
            },
            {
                title:"失败页",
                key:'/admin/result/error',  
                icon:'close'     
            }
        ]  
    },
    {
        title:"失败页",
        key:'/admin/error',
        icon:"warning",
        children:[
            {
                title:"403",
                key:'/admin/error/403',
                icon:'info-circle'       
            },
            {
                title:"404",
                key:'/admin/error/404',
                icon:'info-circle'       
            },
            {
                title:"500",
                key:'/admin/error/500',
                icon:'info-circle'    
            }
        ]    
    },
    {
        title:"个人页",
        key:'/admin/account', 
        icon:"user",
        children:[
            {
                title:"个人中心",
                key:'/admin/account/center',
                icon:"smile",     
            },
            {
                title:"个人设置",
                key:'/admin/account/settings',   
                icon:"smile", 
            }
        ]   
    }
]